python3 /home/mat/Bureau/crypto/BTC.py &
python3 /home/mat/Bureau/crypto/ETH.py &
python3 /home/mat/Bureau/crypto/BNB.py &
python3 /home/mat/Bureau/crypto/XRP.py &
python3 /home/mat/Bureau/crypto/ADA.py &
python3 /home/mat/Bureau/crypto/SOL.py &
python3 /home/mat/Bureau/crypto/DOGE.py &
python3 /home/mat/Bureau/crypto/MATIC.py &
python3 /home/mat/Bureau/crypto/DOT.py &
python3 /home/mat/Bureau/crypto/DAI.py &
python3 /home/mat/Bureau/crypto/SHIB.py &
python3 /home/mat/Bureau/crypto/TRX.py &
python3 /home/mat/Bureau/crypto/AVAX.py &
python3 /home/mat/Bureau/crypto/UNI.py &
python3 /home/mat/Bureau/crypto/WBTC.py &
python3 /home/mat/Bureau/crypto/LEO.py &
python3 /home/mat/Bureau/crypto/LTC.py &
python3 /home/mat/Bureau/crypto/ATOM.py &
python3 /home/mat/Bureau/crypto/LINK.py &
python3 /home/mat/Bureau/crypto/ETC.py &
python3 /home/mat/Bureau/crypto/XLM.py &
python3 /home/mat/Bureau/crypto/FTT.py &
python3 /home/mat/Bureau/crypto/NEAR.py &
python3 /home/mat/Bureau/crypto/CRO.py &
python3 /home/mat/Bureau/crypto/XMR.py &
python3 /home/mat/Bureau/crypto/ALGO.py &
python3 /home/mat/Bureau/crypto/BCH.py &
python3 /home/mat/Bureau/crypto/LUNC.py &
python3 /home/mat/Bureau/crypto/QNT.py &
python3 /home/mat/Bureau/crypto/FLOW.py &
python3 /home/mat/Bureau/crypto/VET.py &
python3 /home/mat/Bureau/crypto/TON.py &
python3 /home/mat/Bureau/crypto/APE.py &
python3 /home/mat/Bureau/crypto/FIL.py &
python3 /home/mat/Bureau/crypto/ICP.py &
python3 /home/mat/Bureau/crypto/HBAR.py &
python3 /home/mat/Bureau/crypto/EGLD.py &
python3 /home/mat/Bureau/crypto/XTZ.py &
python3 /home/mat/Bureau/crypto/MANA.py &
python3 /home/mat/Bureau/crypto/SAND.py &
python3 /home/mat/Bureau/crypto/CHZ.py &
python3 /home/mat/Bureau/crypto/EOS.py &
python3 /home/mat/Bureau/crypto/AAVE.py &
python3 /home/mat/Bureau/crypto/THETA.py &
python3 /home/mat/Bureau/crypto/AXS.py &
python3 /home/mat/Bureau/crypto/USDP.py &
python3 /home/mat/Bureau/crypto/OKB.py &
python3 /home/mat/Bureau/crypto/BSV.py &
python3 /home/mat/Bureau/crypto/TUSD.py &
python3 /home/mat/Bureau/crypto/MKR.py &
python3 /home/mat/Bureau/crypto/KCS.py &
python3 /home/mat/Bureau/crypto/ZEC.py &
python3 /home/mat/Bureau/crypto/USDD.py &
python3 /home/mat/Bureau/crypto/HT.py &
python3 /home/mat/Bureau/crypto/XEC.py &
python3 /home/mat/Bureau/crypto/MIOTA.py &
python3 /home/mat/Bureau/crypto/BTT.py &
python3 /home/mat/Bureau/crypto/USDN.py &
python3 /home/mat/Bureau/crypto/CAKE.py &
python3 /home/mat/Bureau/crypto/GRT.py &
python3 /home/mat/Bureau/crypto/NEO.py &
python3 /home/mat/Bureau/crypto/HNT.py &
python3 /home/mat/Bureau/crypto/KLAY.py &
python3 /home/mat/Bureau/crypto/FTM.py &
python3 /home/mat/Bureau/crypto/PAXG.py &
python3 /home/mat/Bureau/crypto/SNX.py &
python3 /home/mat/Bureau/crypto/RUNE.py &
python3 /home/mat/Bureau/crypto/NEXO.py &
python3 /home/mat/Bureau/crypto/GT.py &
python3 /home/mat/Bureau/crypto/DASH.py &
python3 /home/mat/Bureau/crypto/CRV.py &
python3 /home/mat/Bureau/crypto/BAT.py &
python3 /home/mat/Bureau/crypto/ENJ.py &
python3 /home/mat/Bureau/crypto/LDO.py &
python3 /home/mat/Bureau/crypto/STX.py &
python3 /home/mat/Bureau/crypto/KAVA.py &
python3 /home/mat/Bureau/crypto/COMP.py &
python3 /home/mat/Bureau/crypto/ZIL.py &
python3 /home/mat/Bureau/crypto/FEI.py &
python3 /home/mat/Bureau/crypto/RVN.py &
python3 /home/mat/Bureau/crypto/MINA.py &
python3 /home/mat/Bureau/crypto/WAVES.py &
python3 /home/mat/Bureau/crypto/XDC.py &
python3 /home/mat/Bureau/crypto/USDTC.py &
python3 /home/mat/Bureau/crypto/GMT.py &
python3 /home/mat/Bureau/crypto/TWT.py &
python3 /home/mat/Bureau/crypto/LRC.py &
python3 /home/mat/Bureau/crypto/DCR.py &
python3 /home/mat/Bureau/crypto/CVX.py &
python3 /home/mat/Bureau/crypto/CSPR.py &
python3 /home/mat/Bureau/crypto/XEM.py &
python3 /home/mat/Bureau/crypto/KSM.py &
python3 /home/mat/Bureau/crypto/CELO.py &
python3 /home/mat/Bureau/crypto/BTG.py &
python3 /home/mat/Bureau/crypto/ENS.py &
python3 /home/mat/Bureau/crypto/1INCH.py &
python3 /home/mat/Bureau/crypto/HOT.py &
python3 /home/mat/Bureau/crypto/LUNA.py &
python3 /home/mat/Bureau/crypto/RSR.py &
python3 /home/mat/Bureau/crypto/BNX.py &
python3 /home/mat/Bureau/crypto/GUSD.py &
python3 /home/mat/Bureau/crypto/ROSE.py &
python3 /home/mat/Bureau/crypto/YFI.py &
python3 /home/mat/Bureau/crypto/QTUM.py &
python3 /home/mat/Bureau/crypto/AR.py &
python3 /home/mat/Bureau/crypto/ANKR.py &
python3 /home/mat/Bureau/crypto/GNO.py &
python3 /home/mat/Bureau/crypto/GALA.py &
python3 /home/mat/Bureau/crypto/TFUEL.py &
python3 /home/mat/Bureau/crypto/KDA.py &
python3 /home/mat/Bureau/crypto/IOTX.py &
python3 /home/mat/Bureau/crypto/GLM.py &
python3 /home/mat/Bureau/crypto/BTRST.py &
python3 /home/mat/Bureau/crypto/JST.py &
python3 /home/mat/Bureau/crypto/CEL.py &
python3 /home/mat/Bureau/crypto/POLY.py &
python3 /home/mat/Bureau/crypto/ONE.py &
python3 /home/mat/Bureau/crypto/HIVE.py &
python3 /home/mat/Bureau/crypto/OMG.py &
python3 /home/mat/Bureau/crypto/LPT.py &
python3 /home/mat/Bureau/crypto/ZRX.py &
python3 /home/mat/Bureau/crypto/BAL.py &
python3 /home/mat/Bureau/crypto/FLUX.py &
python3 /home/mat/Bureau/crypto/IOST.py &
python3 /home/mat/Bureau/crypto/ICX.py &
python3 /home/mat/Bureau/crypto/BORA.py &
python3 /home/mat/Bureau/crypto/AMP.py &
python3 /home/mat/Bureau/crypto/XYM.py &
python3 /home/mat/Bureau/crypto/SRM.py &
python3 /home/mat/Bureau/crypto/KNC.py &
python3 /home/mat/Bureau/crypto/ONT.py &
python3 /home/mat/Bureau/crypto/OP.py &
python3 /home/mat/Bureau/crypto/GLMR.py &
python3 /home/mat/Bureau/crypto/CHSB.py &
python3 /home/mat/Bureau/crypto/STORJ.py &
python3 /home/mat/Bureau/crypto/WAXP.py &
python3 /home/mat/Bureau/crypto/SC.py &
python3 /home/mat/Bureau/crypto/WOO.py &
python3 /home/mat/Bureau/crypto/ZEN.py &
python3 /home/mat/Bureau/crypto/XCH.py &
python3 /home/mat/Bureau/crypto/SXP.py &
python3 /home/mat/Bureau/crypto/SUSHI.py &
python3 /home/mat/Bureau/crypto/IMX.py &
python3 /home/mat/Bureau/crypto/MXC.py &
python3 /home/mat/Bureau/crypto/AUDIO.py &
python3 /home/mat/Bureau/crypto/NFT.py &
python3 /home/mat/Bureau/crypto/UMA.py &
python3 /home/mat/Bureau/crypto/PLA.py &
python3 /home/mat/Bureau/crypto/SKL.py &
python3 /home/mat/Bureau/crypto/ABBC.py &
python3 /home/mat/Bureau/crypto/SCRT.py &
python3 /home/mat/Bureau/crypto/SLP.py &
python3 /home/mat/Bureau/crypto/DGB.py &
python3 /home/mat/Bureau/crypto/ELON.py &
python3 /home/mat/Bureau/crypto/INJ.py &
python3 /home/mat/Bureau/crypto/VGX.py &
python3 /home/mat/Bureau/crypto/CKB.py &
python3 /home/mat/Bureau/crypto/CVC.py &
python3 /home/mat/Bureau/crypto/LSK.py &
python3 /home/mat/Bureau/crypto/VLX.py &
python3 /home/mat/Bureau/crypto/PUNDIX.py &
python3 /home/mat/Bureau/crypto/COTI.py &
python3 /home/mat/Bureau/crypto/KEEP.py &
python3 /home/mat/Bureau/crypto/DAO.py &
python3 /home/mat/Bureau/crypto/REN.py &
python3 /home/mat/Bureau/crypto/MED.py &
python3 /home/mat/Bureau/crypto/RNDR.py &
python3 /home/mat/Bureau/crypto/CEEK.py &
python3 /home/mat/Bureau/crypto/REEF.py &
python3 /home/mat/Bureau/crypto/EWT.py &
python3 /home/mat/Bureau/crypto/PEOPLE.py &
python3 /home/mat/Bureau/crypto/BTCST.py &
python3 /home/mat/Bureau/crypto/WIN.py &
python3 /home/mat/Bureau/crypto/NU.py &
python3 /home/mat/Bureau/crypto/CELR.py &
python3 /home/mat/Bureau/crypto/SYS.py &
python3 /home/mat/Bureau/crypto/ONG.py &
python3 /home/mat/Bureau/crypto/XNO.py &
python3 /home/mat/Bureau/crypto/REQ.py &
python3 /home/mat/Bureau/crypto/DAG.py &
python3 /home/mat/Bureau/crypto/ORBS.py &
python3 /home/mat/Bureau/crypto/SPELL.py &
python3 /home/mat/Bureau/crypto/RLC.py &
python3 /home/mat/Bureau/crypto/OCEAN.py &
python3 /home/mat/Bureau/crypto/API3.py &
python3 /home/mat/Bureau/crypto/SNT.py &
python3 /home/mat/Bureau/crypto/TRIBE.py &
python3 /home/mat/Bureau/crypto/ARDR.py &
python3 /home/mat/Bureau/crypto/PYR.py &
python3 /home/mat/Bureau/crypto/FX.py &
python3 /home/mat/Bureau/crypto/UOS.py &
python3 /home/mat/Bureau/crypto/POWER.py &
python3 /home/mat/Bureau/crypto/ACA.py &
python3 /home/mat/Bureau/crypto/PROM.py &
python3 /home/mat/Bureau/crypto/DENT.py &
python3 /home/mat/Bureau/crypto/CHR.py &
python3 /home/mat/Bureau/crypto/MX.py
